// Generated by CoffeeScript 1.10.0
(function() {
  var babelify, browserSync, browserify, coffeeify, config, cssmin, del, gulp, htmlmin, imagemin, reload, runSequence, source, targetFolder, uglify, usemin, vueify;

  gulp = require("gulp");

  browserify = require("browserify");

  reactify = require('reactify')

  source = require("vinyl-source-stream");

  del = require("del");

  browserSync = require("browser-sync");

  reload = browserSync.reload;

  runSequence = require('run-sequence');

  usemin = require("gulp-usemin");

  uglify = require("gulp-uglify");

  cssmin = require("gulp-minify-css");

  imagemin = require('gulp-imagemin');

  htmlmin = require('gulp-htmlmin');



  config = {
    srcFolder: "./app",
    tmpFolder: "_tmp",
    releaseFolder: "_dist",
    port: 9001
  };

  targetFolder = config.tmpFolder;

  gulp.task("browserify", function() {
    return browserify({
      entries: [config.srcFolder + "/scripts/index.js"],
    }).transform(reactify).bundle().pipe(source("bundle.js")).pipe(gulp.dest(targetFolder + "/scripts"));
  });

  gulp.task('images', function() {
    return gulp.src(config.srcFolder + "/images/**/*").pipe(imagemin({
      optimizationLevel: 5,
      progressive: true,
      interlaced: true
    })).pipe(gulp.dest(targetFolder + "/images"));
  });

  gulp.task("cssmin", function() {
    return gulp.src(targetFolder + "/styles/*.css").pipe(cssmin()).pipe(gulp.dest(targetFolder + "/styles"));
  });

  gulp.task("uglify", function() {
    return gulp.src(targetFolder + "/scripts/*.js").pipe(uglify()).pipe(gulp.dest(targetFolder + "/scripts"));
  });

  gulp.task("htmlmin", function() {
    return gulp.src(targetFolder + "/index.html").pipe(htmlmin({
      collapseWhitespace: true
    })).pipe(gulp.dest("" + targetFolder));
  });

  gulp.task("usemin", function() {
    return gulp.src(config.srcFolder + "/index.html").pipe(usemin()).pipe(gulp.dest("" + targetFolder));
  });

  gulp.task("watch", function() {
    gulp.watch([config.srcFolder + "/scripts/**/*.*"], ["browserify"]);
    gulp.watch([config.srcFolder + "/index.html", config.srcFolder + "/styles/**/*.css"], ["usemin"]);
    gulp.watch([config.srcFolder + "/images/**/*"], ['images']);
    return gulp.watch([targetFolder + "/**/*"], reload);
  });

  gulp.task("server", function() {
    browserSync({
      server: {
        baseDir: "" + targetFolder
      },
      port: config.port
    });
    return console.log("server start at " + config.port + "...");
  });

  gulp.task("build", function() {
    targetFolder = config.releaseFolder;
    return runSequence('clean', ["browserify", "usemin", 'images'], ["cssmin", "uglify", 'htmlmin']);
  });

  gulp.task('dev', function() {
    targetFolder = config.tmpFolder;
    return runSequence('clean', ["browserify", "images", "usemin"], ['server', "watch"]);
  });

  gulp.task("default", ['dev'], function() {
    return console.log('=======run task=======');
  });

  gulp.task("clean", function(arg) {
    return del([targetFolder]);
  });

}).call(this);
